apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: oracle-credential
spec:
  path: secret/ad/accel-webapp/smart-captar/oracle-credential
  type: Opaque
  keys:
    - USER
    - PASSWORD
  templates:
    ".env": |
      USER={% .Secrets.USER %}
      PASSWORD={% .Secrets.PASSWORD %}